### ISSUE TITLE
Servidor - Etiquetas del disparador se desmaqueta

### ISSUE THREAD

**Issue by AlexMor97** [zahori-io/zahori-server#69]
Probado en resolución de portátil, cuando tenemos muchas etiquetas configuradas, en la pantalla del disparador, podemos ver que estas se desmaquetan, superponiéndose al apartado derecho "Ejecución"

![Image](https://github.com/zahori-io/zahori-server/assets/29733963/4fb9cf98-0c11-4c58-9023-f74df4d832eb)

El funcionamiento correcto sería que las etiquetas se adapten a la resolución de la pantalla, y las que no quepen se vayan poniendo justo por debajo.

![Image](https://github.com/zahori-io/zahori-server/assets/29733963/0e7bdd78-4a4e-4f29-a50a-23bbcfff1783)

**Comment by davidvazqu3z** [comment]
Corregido en la versión: 0.1.20
